version: '3'

services:
  db:
    image: "postgres"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  server:
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - './server:/usr/src/app'
      - 'server/usr/src/app/node_modules'
    ports:
      - '8081:8080'
    environment:
      - NODE_ENV=development
  client:
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - './client:/app'
      - 'client/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development    