version: '3'

services:

  client:
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - './client:/app'
      - 'client/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
  
  server:
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - './server:/usr/src/app'
      - 'server/usr/src/app/node_modules'
    ports:
      - '8081:8080'
    environment:
      - NODE_ENV=development